### ISSUE TITLE
Handling side-effects

### ISSUE THREAD

**Issue by stepanzalis** [zsmb13/ViewStateDemos#2]
Hey, first of all thank you for the great blog post. My question is, how would you handle side-effects (like a showing a Dialog, SnackBar etc.)?

**Comment by zsmb13** [comment]
I use variations of what's usually referred to as `SingleLiveEvent`, but that's all outside the ViewState, and this sample and article only focuses on the state management side of things. I will be covering both state and event handling in more detail in upcoming articles over the next few weeks.
